// frontend/components/home/ProjectEntry.tsx
import Image from 'next/image';
import Link from 'next/link';
import styles from './ProjectEntry.module.css';

interface ProjectEntryProps {
  imgSrc: string;
  projTitle: string;
  descText: string;
  projLink: string;
  linkText: string;
}

export default function ProjectEntry({ imgSrc, projTitle, descText, projLink, linkText }: ProjectEntryProps) {
  const isExternal = linkText !== 'Live Project';
  const linkProps = isExternal ? { target: '_blank' as const, rel: 'noopener noreferrer' } : {};
  const LinkTag: typeof Link | 'a' = isExternal ? 'a' : Link;

  return (
    <div className={styles['project-container']}>
      <div style={{ display: 'flex', justifyContent: 'center' }}>
        <LinkTag href={projLink} {...linkProps}>
          <Image src={imgSrc} className={styles['preview-img']} alt={projTitle} width={192} height={192} />
        </LinkTag>
      </div>

      <div className={styles['description-box']}>
        <div className={styles['project-title']}>
          <b dangerouslySetInnerHTML={{ __html: projTitle }} />
        </div>
        <br />
        <div className={styles['description-text']} dangerouslySetInnerHTML={{ __html: descText }} />
        <br />
        <div className={styles['project-link']}>
          <LinkTag href={projLink} {...linkProps}>&lt;{linkText}&gt;</LinkTag>
        </div>
      </div>
    </div>
  );
}

// frontend/src/lib/components/ProjectEntry.svelte
<script>

    let {imgSrc, projTitle, descText, projLink, linkText} = $props();

</script>

<div class="project-container">
    {#if linkText !== "Live Project"}
    <a href={projLink} target="_blank" rel="noopener noreferrer"><img src={imgSrc} class="preview-img"></a>
    {:else}
    <a href={projLink}><img src={imgSrc} class="preview-img"></a>
    {/if}
    
    <div class="description-box">
        <div class="project-title"><b>{@html projTitle}</b></div>
        <br />
        <div class="description-text">{@html descText}</div>
        <br />
        {#if linkText !== "Live Project"}
         <div class="project-link"><a href={projLink} target="_blank" rel="noopener noreferrer">&lt;{linkText}&gt;</a></div>
        {:else}
        <div class="project-link"><a href={projLink}>&lt;{linkText}&gt;</a></div>
        {/if}
        
    </div>
</div>

<style>
    .project-container {
        display: flex;
        justify-content: center;
        margin-top: 1.5em;
    }

    .preview-img {
        width: 12em;
        height: 12em;
        border: .1em solid white;
        border-radius: 1em;
    }

    .description-box {
        width: calc(100% - 12em);
        padding: 1em 3em;
    }

    .project-title {
        font-size: 1.5em;
    }

</style>
